spring.datasource.url=jdbc:mysql://localhost:3306/mindmitra
spring.datasource.username=root
spring.datasource.password=root
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
openrouter.api.key={your-api-key-here}